version: "3.7"
services:
    # mongodb:
    #     image: mongo
    #     container_name: mongodb
    #     restart: always
    #     env_file: .env
    #     volumes:
    #         - data:/data/db
    #     expose:
    #         - 27017
    #     # ports:
    #     #     - 27023:27017
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: ${PL_DATA_MONGODB_USERNAME}
    #         MONGO_INITDB_ROOT_PASSWORD: ${PL_DATA_MONGODB_PASSWORD}
    server:
        image: padloc/server
        build:
            context: .
            dockerfile: Dockerfile-server
        # depends_on:
        #     - mongodb
        env_file: .env
        # environment:
        #     PL_DATA_MONGODB_HOST: mongodb
        #     PL_DATA_MONGODB_PROTOCOL: mongodb
        #     PL_DATA_MONGODB_PORT: 27017
        #     PL_DATA_ATTACHMENTS_BACKEND: fs
        #     PL_DATA_ATTACHMENTS_DIR: /attachments
        environment:
            - PL_ASSETS_DIR=/assets
        expose:
            - 3000
            - 4000
        volumes:
            - attachments:/attachments
            - logs:/logs
            - ${PL_ASSETS_DIR:-./assets}:/assets
        restart: unless-stopped
    pwa:
        image: padloc/pwa
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile-pwa
        volumes:
            - pwa:/pwa
            - ${PL_ASSETS_DIR:-./assets}:/assets
        environment:
            - PL_ASSETS_DIR=/assets
        command: ["build"]
        restart: on-failure
    nginx:
        env_file: .env
        environment:
            - API_KEY=${PL_AMPLIFY_API_KEY}
            - AMPLIFY_IMAGENAME=${PL_HOSTNAME}
        build:
            context: ./nginx
            dockerfile: Dockerfile
        depends_on:
            - server
        restart: always
        volumes:
            - pwa:/pwa
            # - logs:/var/log
            - /var/www/certbot:/certbot
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ${PL_SSL_CERT}:/ssl/cert
            - ${PL_SSL_KEY}:/ssl/key
            - /etc/letsencrypt/options-ssl-nginx.conf:/ssl/ssl.conf
            - /etc/letsencrypt/ssl-dhparams.pem:/ssl/dhparams.pem
        ports:
            - 80:80
            - 443:443
volumes:
    data:
    attachments:
    pwa:
    logs:
